Fix unused values error on Travis CI
It seems that it complains in the travis environment:

/home/travis/build/legatoproject/workspace/legato/apps/platformServices/airVantageConnector/avcClient/osPortSecurity.c:
In function ‘lwm2mcore_Base64Encode’:
/home/travis/build/legatoproject/workspace/legato/apps/platformServices/airVantageConnector/avcClient/osPortSecurity.c:327:5:
error: value computed is not used [-Werror=unused-value]
     BIO_flush(bio);
     ^
/home/travis/build/legatoproject/workspace/legato/apps/platformServices/airVantageConnector/avcClient/osPortSecurity.c:329:5:
error: value computed is not used [-Werror=unused-value]
     BIO_set_close(bio, BIO_NOCLOSE);
     ^
cc1: all warnings being treated as errors

Fixing this by asserting on the result of these functions.

Resolves: LE-11220
Change-Id: I82c269b45a348d68a0c5b46e91890444eecfbd24